apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemisAddress
metadata:
  name: prfccumulussimulator.delivery
spec:
  addressName: prfccumulussimulator.delivery
  queueName: prfccumulussimulator.delivery
  routingType: anycast
